#!/bin/bash --login
# ----------------------------------------------------------- 
# UNIX Shell Script File
# Tested Operating System(s): RHEL 5,6
# Tested Run Level(s): 3, 5
# Shell Used: BASH shell
# Original Author(s): Roberto Padilla-Hernandez
# File Creation Date: 02/01/2015
# Date Last Modified:
#
# Version control: 1.14
#
# Support Team:
#
# Contributors: Floyd fayton
#
# ----------------------------------------------------------- 
# ------------- Program Description and Details ------------- 
# ----------------------------------------------------------- 
#
# Job Card to set the resources required for a NWPS run
#
# -----------------------------------------------------------

#PBS -N gyx_po_cgn
#PBS -j oe
#PBS -S /bin/bash
#PBS -q dev_transfer
#PBS -A NWPS-DEV
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=1
#PBS -l debug=true
#PBS -V
#PBS -o /u/andre.vanderwesthuysen/nwps_gyx_post_cgn.o
#PBS -e /u/andre.vanderwesthuysen/nwps_gyx_post_cgn.o

cd $PBS_O_WORKDIR

module load intel/19.1.3.304
module load wgrib2/2.0.8
module load proj/7.1.0
module load geos/3.8.1
module load libjpeg/9c
module load python/3.8.6

module list

export workdir=/lfs/h2/emc/couple/noscrub/andre.vanderwesthuysen/nwps_para/var_offline_dev
export comroot=/lfs/h2/emc/ptmp/andre.vanderwesthuysen/com/nwps/v1.5.0

${workdir}/plot_cgn_fields_wfo.sh "er" "gyx" > ${workdir}/plot_cgn_fields_gyx.log 2>&1

