#!/bin/sh
date
export PS4='$SECONDS ${0/\/nw.*\/nwps.*\/} + '
set -xa

export DBNROOT=${UTILROOT}/para_dbn
# #### 04/01/15 ###############################
# SETUP NWPS SHELL VARIABLES
# #############################################
#export DATA=${DATA:-${DATAROOT}/${jobid}}
export DATA=$DATAROOT/p${model}_${WFO}_${envir}
rm -rf $DATA
mkdir $DATA
cd $DATA

curhour=$(date -u +%H)
if [ $curhour -lt 12 ]; then CYCLE="00"; fi
if [ $curhour -ge 12 ] && [ $curhour -lt 18 ]; then CYCLE="06"; fi
if [ $curhour -ge 18 ] && [ $curhour -lt 22 ]; then CYCLE="12"; fi
if [ $curhour -ge 22 ]; then CYCLE="18"; fi
echo ""
echo "INFO - Current hour is ${curhour}, setting model cycle to ${CYCLE}"
export cyc=${CYCLE}
export cycle=t${cyc}z

####################################
# Specify NET and RUN Name and model
####################################
export NET=${model}
export OFS=ofs
export RUN=$(echo ${job}|awk -F"_" '{print $2}')

####################################
# SENDECF  - Flag Events on ECFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEnwps=${NWROOT}/${model}.${nwps_ver}
export FIXnwps=${FIXnwps:-${HOMEnwps}/fix}
export EXECnwps=${EXECnwps:-${HOMEnwps}/exec}
export SORCnwps=${SORCnwps:-${HOMEnwps}/sorc}
export PARMnwps=${PARMnwps:-${HOMEnwps}/parm}
export USHnwps=${USHnwps:-${HOMEnwps}/ush}
export PMnwps=${PMnwps:-${USHnwps}/pm}
export BATHYdb=${BATHYdb:-${FIXnwps}/bathy_db}
export SHAPEFILEdb=${SHAPEFILEdb:-${FIXnwps}/shapefile_db}

# Set processing DIRs here
export ARCHdir=${ARCHdir:-${DATA}/archive}
export DATAdir=${DATAdir:-${DATA}/data}
export INPUTdir=${INPUTdir:-${DATA}/input}
export VARdir=${VARdir:-${DATA}/var}
export OUTPUTdir=${OUTPUTdir:-${DATA}/output}
export RUNdir=${RUNdir:-${DATA}/run}
export TMPdir=${TMPdir:-${DATA}/tmp}
export LOGdir=${LOGdir:-${DATA}/logs}
export GEN_NETCDF=${GEN_NETCDF:-FALSE}
export GEN_HDF5=${GEN_HDF5:-FALSE}
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${HOMEnwps}/lib/szip:${HOMEnwps}/lib/proj
export PYTHONPATH=${HOMEnwps}/lib/python/python_modules/lib64/python2.6/site-packages:${HOMEnwps}/lib/basemap:${PYTHONPATH}
export PYTHON=python

# Set NWPS run conditions
export DEBUGGING=${DEBUGGING:-TRUE}
export DEBUG_LEVEL=${DEBUG_LEVEL:-1}
export ISPRODUCTION=${ISPRODUCTION:-TRUE}
export SITETYPE=${SITETYPE:-EMC}
export MODELTYPE="SWAN"

export pgmout=OUTPUT.$$
setpdy.sh
. ./PDY

##############################################
# Define COM directory
##############################################
export COMIN=${COMROOT}/${NET}/${envir}/${WFO}.${PDY}
export COMINm1=${COMROOT}/${NET}/${envir}/${WFO}.${PDYm1}
export COMINm2=${COMROOT}/${NET}/${envir}/${WFO}.${PDYm2}
export COMINm3=${COMROOT}/${NET}/${envir}/${WFO}.${PDYm3}
export COMOUT=${COMROOT}/${NET}/${envir}/${WFO}.${PDY}
export GESIN=${GESROOT}/${envir}/${NET}.${PDY}
export GESINm1=${GESROOT}/${envir}/${NET}.${PDYm1}
export GESINm2=${GESROOT}/${envir}/${NET}.${PDYm2}
export GESOUT=${GESROOT}/${envir}/${NET}.${PDY}
export GESOUTm1=${GESROOT}/${envir}/${NET}.${PDYm1}
export GESOUTm2=${GESROOT}/${envir}/${NET}.${PDYm2}
export COMINgfs=${COMROOT}/gfs/prod/gfs.${PDY}
export COMINwave=${COMROOT}/wave/prod
#export COMINestofs=${COMROOT}/estofs/prod/estofs.${PDY}
#export COMINrtofs=${COMROOT}/rtofs/prod/rtofs.${PDY}
#----Suggested paths for OFS PREP output (see get_ncep_initfiles.sh)-------
export COMINestofs=/com/${NET}/${envir}/ofs.${PDY}/estofs/${WFO}_output
export COMINestofsm1=/com/${NET}/${envir}/ofs.${PDYm1}/estofs/${WFO}_output
export COMINrtofs=/com/${NET}/${envir}/ofs.${PDY}/rtofs/${WFO}_output
export COMINrtofsm1=/com/${NET}/${envir}/ofs.${PDYm1}/rtofs/${WFO}_output
export COMINpsurge=/com/${NET}/${envir}/ofs.${PDY}/psurge/${WFO}_output
export COMINpsurgem1=/com/${NET}/${envir}/ofs.${PDYm1}/psurge/${WFO}_output
#--------------------------------------------------------------------------
export dcom=${dcom:-/dcom/us007003}
export FORECASTWINDdir="${dcom}/${PDY}/wgrbbul/${NET}"
export PCOM=/pcom/${NET}
# make sure NWPS COM directory exists
if [ "${SENDCOM}" = YES ]; then
    mkdir -p $COMOUT
fi

mkdir -p $COMIN $COMOUT $LOGdir $RUNdir $TMPdir $OUTPUTdir $ARCHdir $DATAdir $INPUTdir $VARdir $GESOUT

##############################################
# Execute the script
${HOMEnwps}/scripts/exnwps_prep.sh.ecf
export err=$?; err_chk
##############################################


msg="JOB $job HAS COMPLETED NORMALLY."
postmsg $jlogfile "$msg"

if [ -e $pgmout ]; then
    cat $pgmout
fi

cd $DATAROOT

date
