#!/bin/sh
date
export PS4='$SECONDS ${0/\/nw.*\/nwps.*\/} + '
set -xa

# #############################################
# SETUP NWPS SHELL VARIABLES
# #############################################
export DATA=$DATAROOT/p${model}_${WFO}_${envir}
rm -rf $DATA
mkdir $DATA
cd $DATA

curhour=$(date -u +%H)
if [ $curhour -lt 12 ]; then CYCLE="00"; fi
if [ $curhour -ge 12 ] && [ $curhour -lt 18 ]; then CYCLE="06"; fi
if [ $curhour -ge 18 ] && [ $curhour -lt 22 ]; then CYCLE="12"; fi
if [ $curhour -ge 22 ]; then CYCLE="18"; fi
echo ""
echo "INFO - Current hour is ${curhour}, setting model cycle to ${CYCLE}"
export cyc=${CYCLE}
export cycle=t${cyc}z

####################################
# Specify NET and RUN Name and model
####################################
export NET=${model}
export OFS=ofs
export RUN=$(echo ${job}|awk -F"_" '{print $2}')

####################################
# SENDECF  - Flag Events on ECFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEnwps=${HOMEnwps:-${PACKAGEROOT}/${model}.${nwps_ver}}
export FIXnwps=${FIXnwps:-${HOMEnwps}/fix}
export EXECnwps=${EXECnwps:-${HOMEnwps}/exec}
export SORCnwps=${SORCnwps:-${HOMEnwps}/sorc}
export PARMnwps=${PARMnwps:-${HOMEnwps}/parm}
export USHnwps=${USHnwps:-${HOMEnwps}/ush}
export PMnwps=${PMnwps:-${USHnwps}/pm}
export BATHYdb=${BATHYdb:-${FIXnwps}/bathy_db}
export SHAPEFILEdb=${SHAPEFILEdb:-${FIXnwps}/shapefile_db}

# Set processing DIRs here
export ARCHdir=${ARCHdir:-${DATA}/archive}
export DATAdir=${DATAdir:-${DATA}/data}
export INPUTdir=${INPUTdir:-${DATA}/input}
export VARdir=${VARdir:-${DATA}/var}
export OUTPUTdir=${OUTPUTdir:-${DATA}/output}
export RUNdir=${RUNdir:-${DATA}/run}
export TMPdir=${TMPdir:-${DATA}/tmp}
export LOGdir=${LOGdir:-${DATA}/logs}
export GEN_NETCDF=${GEN_NETCDF:-FALSE}
export GEN_HDF5=${GEN_HDF5:-FALSE}
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${HOMEnwps}/lib/szip:${HOMEnwps}/lib/proj

# Set NWPS run conditions
export RETROSPECTIVE=${RETROSPECTIVE:-FALSE}
export DEBUGGING=${DEBUGGING:-TRUE}
export DEBUG_LEVEL=${DEBUG_LEVEL:-1}
export ISPRODUCTION=${ISPRODUCTION:-TRUE}
export SITETYPE=${SITETYPE:-EMC}
export MODELTYPE="SWAN"

export pgmout=OUTPUT.$$
setpdy.sh
. ./PDY

# Determine WFO's Region
export REGION=$( grep ${WFO,,} ${PARMnwps}/wfo.tbl | cut -c1-2 | tr '[:upper:]' '[:lower:]' )

##############################################
# Define COM directory
##############################################
export COMIN=$(compath.py ${NET}/${nwps_ver}/${REGION}.${PDY}/${WFO})
export COMINm1=$(compath.py ${NET}/${nwps_ver}/${REGION}.${PDYm1}/${WFO})
export COMINm2=$(compath.py ${NET}/${nwps_ver}/${REGION}.${PDYm2}/${WFO})
export COMINm3=$(compath.py ${NET}/${nwps_ver}/${REGION}.${PDYm3}/${WFO})
export COMOUT=$(compath.py -o ${NET}/${nwps_ver}/${REGION}.${PDY}/${WFO})

export GESIN=$(compath.py ${NET}/${nwps_ver}/${NET}.${PDY}/nwges)
export GESINm1=$(compath.py ${NET}/${nwps_ver}/${NET}.${PDYm1}/nwges)
export GESINm2=$(compath.py ${NET}/${nwps_ver}/${NET}.${PDYm2}/nwges)
export GESOUT=$(compath.py -o ${NET}/${nwps_ver})/${NET}.${PDY}/nwges
export GESOUTm1=$(compath.py -o ${NET}/${nwps_ver})/${NET}.${PDYm1}/nwges
export GESOUTm2=$(compath.py -o ${NET}/${nwps_ver})/${NET}.${PDYm2}/nwges

export COMINgfs=${COMINgfs:-$(compath.py prod/gfs/${gfs_ver}/gfs.${PDY})}
export COMINgfsm1=${COMINgfsm1:-$(compath.py prod/gfs/${gfs_ver}/gfs.${PDYm1})}
export COMINwave=${COMINwave:-$(compath.py prod/gfs/${gfs_ver})}
export COMINestofs=$(compath.py ${NET}/${nwps_ver}/ofs.${PDY}/estofs/${WFO}_output)
export COMINestofsm1=$(compath.py ${NET}/${nwps_ver}/ofs.${PDYm1}/estofs/${WFO}_output)
export COMINrtofs=$(compath.py ${NET}/${nwps_ver}/ofs.${PDY}/rtofs/${WFO}_output)
export COMINrtofsm1=$(compath.py ${NET}/${nwps_ver}/ofs.${PDYm1}/rtofs/${WFO}_output)
export COMINpsurge=$(compath.py ${NET}/${nwps_ver}/ofs.${PDY}/psurge/${WFO}_output)
export COMINpsurgem1=$(compath.py ${NET}/${nwps_ver}/ofs.${PDYm1}/psurge/${WFO}_output)
#--------------------------------------------------------------------------
export dcom=${dcom:-${DCOMROOT}}

export FORECASTWINDdir="${dcom}/${PDY}/wgrbbul/${NET}"
export COMOUTwmo=$(compath.py -o ${NET}/${nwps_ver})/${REGION}.${PDY}/wmo
export dcom_hist="$GESOUT/dcom_hist.txt"

# make sure NWPS COM directory exists
if [ "${SENDCOM}" = YES ]; then
    mkdir -p $COMOUT
fi

mkdir -p $COMIN $COMOUT $LOGdir $RUNdir $TMPdir $OUTPUTdir $ARCHdir $DATAdir $INPUTdir $VARdir $GESOUT

env

##############################################
# Execute the script
${HOMEnwps}/scripts/exnwps_prep.sh
export err=$?; err_chk
##############################################

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg $jlogfile "$msg"

if [ -e $pgmout ]; then
    cat $pgmout
fi

cd $DATAROOT

date
