#!/bin/sh
date
export PS4='$SECONDS ${0/\/nw.*\/nwps.*\/} + '
set -xa

export DBNROOT=${UTILROOT}/para_dbn
# #### 04/01/15 ###############################
# SETUP NWPS SHELL VARIABLES
# #############################################
export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir $DATA
cd $DATA

####################################
# Specify NET and RUN Name and model
####################################
export NET=${model}
export OFS=ofs
export RUN=${OFSTYPE:-${OFSTYPE:?}}

####################################
# SENDECF  - Flag Events on ECFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

####################################
# Specify Execution Areas
####################################
export HOMEnwps=${NWROOT}/${model}.${nwps_ver}
export FIXnwps=${FIXnwps:-${HOMEnwps}/fix}
export EXECnwps=${EXECnwps:-${HOMEnwps}/exec}
export SORCnwps=${SORCnwps:-${HOMEnwps}/sorc}
export PARMnwps=${PARMnwps:-${HOMEnwps}/parm}
export USHnwps=${USHnwps:-${HOMEnwps}/ush}
export PMnwps=${PMnwps:-${USHnwps}/pm}
export BATHYdb=${BATHYdb:-${FIXnwps}/bathy_db}
export SHAPEFILEdb=${SHAPEFILEdb:-${FIXnwps}/shapefile_db}

# Set processing DIRs here
export ARCHdir=${ARCHdir:-${DATA}/archive}
export DATAdir=${DATAdir:-${DATA}/data}
export INPUTdir=${INPUTdir:-${DATA}/input}
export VARdir=${VARdir:-${DATA}/var}
export OUTPUTdir=${OUTPUTdir:-${DATA}/output}
export RUNdir=${RUNdir:-${DATA}/run}
export TMPdir=${TMPdir:-${DATA}/tmp}
export LOGdir=${LOGdir:-${DATA}/logs}
export GEN_NETCDF=${GEN_NETCDF:-TRUE}
export GEN_HDF5=${GEN_HDF5:-TRUE}
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${HOMEnwps}/lib/szip:${HOMEnwps}/lib/proj
export PYTHONPATH=${HOMEnwps}/lib/python/python_modules/lib64/python2.6/site-packages:${HOMEnwps}/lib/basemap:${PYTHONPATH}
export PYTHON=python

# Set NWPS run conditions
export DEBUGGING=${DEBUGGING:-TRUE}
export DEBUG_LEVEL=${DEBUG_LEVEL:-1}
export ISPRODUCTION=${ISPRODUCTION:-TRUE}
export SITETYPE=${SITETYPE:-EMC}
export MODELTYPE="SWAN"

export TS_f=3600
export pgmout=OUTPUT.$$
setpdy.sh
. ./PDY

##############################################
# Define COM directory
##############################################
export COMROOTp2=/com2
export COMIN=${COMROOT}/${NET}/${envir}/${OFS}.${PDY}
export COMINm1=${COMROOT}/${NET}/${envir}/${WFO}.${PDYm1}
export COMINm2=${COMROOT}/${NET}/${envir}/${WFO}.${PDYm2}
export COMINm3=${COMROOT}/${NET}/${envir}/${WFO}.${PDYm3}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${OFS}.${PDY}}
export GESOUT=${GESROOT}/${envir}/${NET}.${PDY}
export COMINgfs=${COMROOT}/gfs/prod/gfs.${PDY}
export COMINwave=${COMROOT}/wave/prod
export COMINestofs=${COMROOT}/estofs/prod/estofs.${PDY}
export COMINrtofs=${COMROOT}/rtofs/prod/rtofs.${PDY}
export dcom=${dcom:-/dcom/us007003}
#export COMINpsurge=${COMROOTp2}/nhc/${envir}/psurge.${PDY}
export COMINpsurge=${COMROOTp2}/nhc/prod/psurge.${PDY}
#
# make sure NWPS COM directory exists
if [ "${SENDCOM}" = YES ]; then
    mkdir -p $COMOUT
fi

mkdir -p $COMIN $LOGdir $RUNdir $TMPdir $OUTPUTdir $ARCHdir $DATAdir $INPUTdir $VARdir $GESOUT

##############################################
# Execute the script
${HOMEnwps}/scripts/exnwps_ofs_prep.sh.ecf
export err=$?; err_chk
##############################################

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg $jlogfile "$msg"

if [ -e $pgmout ]; then
    cat $pgmout
fi

cd $DATAROOT

if [ "$KEEPDATA" != YES ]; then
    rm -rf $DATA
fi

date
