#!/bin/bash
# ----------------------------------------------------------- 
# UNIX Shell Script File
# Tested Operating System(s): RHEL 5,6
# Tested Run Level(s): 3, 5
# Shell Used: BASH shell
# Original Author(s): Roberto Padilla-Hernandez
# File Creation Date: 02/01/2015
# Date Last Modified:
#
# Version control: 1.00
#
# Support Team:
#
# Contributors: Floyd fayton
#
# ----------------------------------------------------------- 
# ------------- Program Description and Details ------------- 
# ----------------------------------------------------------- 
#
# Sets all environmental variables
#
# ----------------------------------------------------------- 

date
export PS4='$SECONDS ${0/\/nw.*\/nwps.*\/} + '
set -xa
# #### 04/01/15 ###############################
# SETUP NWPS SHELL VARIABLES
# #############################################

#curhour=$(date -u +%H)
#if [ $curhour -lt 12 ]; then CYCLE="00"; fi
#if [ $curhour -ge 12 ] && [ $curhour -lt 18 ]; then CYCLE="06"; fi
#if [ $curhour -ge 18 ] && [ $curhour -lt 22 ]; then CYCLE="12"; fi
#if [ $curhour -ge 22 ]; then CYCLE="18"; fi
#echo ""
#echo "INFO - Current hour is ${curhour}, setting model cycle to ${CYCLE}"

cd /gpfs/hps3/ptmp/${DEVWCOSS_USER}/data/retro

#export cyc=${CYCLE}
export cyc=`cat CYC.${WFO^^}`
export cycle=t${cyc}z

export UTILROOT=/gpfs/hps/nco/ops/nwprod/prod_util.v1.0.12

cd /gpfs/hps3/ptmp/${DEVWCOSS_USER}/data/retro

export utilscript=${UTILROOT}/ush
export USHutil=${UTILROOT}/ush
. ./PDY.${WFO^^}

export pgm="NWPS"

export DATA=/gpfs/hps3/ptmp/${DEVWCOSS_USER}/data/retro/${WFO}.${PDY}
export GESROOT=/gpfs/hps3/ptmp/${DEVWCOSS_USER}/data/retro/nwges

mkdir -p $DATA
cd $DATA


####################################
# Specify NET and RUN Name and model
####################################
export NET=${model}
export OFS=ofs
export RUN=$(echo ${job}|awk -F"_" '{print $2}')

####################################
# SENDECF  - Flag Events on ECFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
#export HOMEnwps=${NWROOT}/${model}.${nwps_ver}
export HOMEnwps=${NWROOT}
export FIXnwps=${FIXnwps:-${HOMEnwps}/fix}
export EXECnwps=${EXECnwps:-${HOMEnwps}/exec}
export SORCnwps=${SORCnwps:-${HOMEnwps}/sorc}
export PARMnwps=${PARMnwps:-${HOMEnwps}/parm}
export USHnwps=${USHnwps:-${HOMEnwps}/ush}
export PMnwps=${PMnwps:-${USHnwps}/pm}
export BATHYdb=${BATHYdb:-${FIXnwps}/bathy_db}
export SHAPEFILEdb=${SHAPEFILEdb:-${FIXnwps}/shapefile_db}

# Set processing DIRs here
export ARCHdir=${ARCHdir:-${DATA}/archive}
export DATAdir=${DATAdir:-${DATA}/data}
export INPUTdir=${INPUTdir:-${DATA}/input}
export VARdir=${VARdir:-${DATA}/var}
export OUTPUTdir=${OUTPUTdir:-${DATA}/output}
export RUNdir=${RUNdir:-${DATA}/run}
export TMPdir=${TMPdir:-${DATA}/tmp}
export LOGdir=${LOGdir:-${DATA}/logs}
export GEN_NETCDF=${GEN_NETCDF:-FALSE}
export GEN_HDF5=${GEN_HDF5:-FALSE}
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${HOMEnwps}/lib/szip:${HOMEnwps}/lib/proj

# Set paths for local Python modules (mesh interpolation)
#export PYTHONPATH=${HOMEnwps}/lib/python/python_modules/lib64/python2.6/site-packages:${PYTHONPATH}
export PYTHONPATH=${HOMEnwps}/lib64/python/python_modules/lib64/python2.6/site-packages:${PYTHONPATH}
export PYTHON=python

# Set NWPS run conditions
export DEBUGGING=${DEBUGGING:-TRUE}
export DEBUG_LEVEL=${DEBUG_LEVEL:-1}
export ISPRODUCTION=${ISPRODUCTION:-TRUE}
export SITETYPE=${SITETYPE:-EMC}
export MODELTYPE="SWAN"
export pgmout=${RUNdir}/PRINT-001
export errfile=${RUNdir}/Errfile-001
export MODELCORE=`grep SWAN ${RUNdir}/info_to_nwps_coremodel.txt`

# Determine WFO's Region
export REGION=$( grep ${WFO,,} ${PARMnwps}/wfo.tbl | cut -c1-2 | tr '[:upper:]' '[:lower:]' )
echo ${REGION}

##############################################
# Define COM directory
##############################################
export COMIN=${COMROOT}/${NET}/${envir}/${REGION}.${PDY}/${WFO}
export COMINm1=${COMROOT}/${NET}/${envir}/${REGION}.${PDYm1}/${WFO}
export COMINm2=${COMROOT}/${NET}/${envir}/${REGION}.${PDYm2}/${WFO}
export COMINm3=${COMROOT}/${NET}/${envir}/${REGION}.${PDYm3}/${WFO}
export COMOUT=${COMROOT}/${NET}/${envir}/${REGION}.${PDY}/${WFO}
export GESOUT=${GESROOT}/${envir}/${NET}.${PDY}
#export COMINgfs=${COMROOT}/gfs/prod/gfs.${PDY}
export COMINwave=${COMROOTp1}/wave/prod
export COMINestofs=${COMROOT}/${NET}/${envir}/ofs.${PDY}/estofs/${WFO}_output
export COMINestofsm1=${COMROOT}/${NET}/${envir}/ofs.${PDYm1}/estofs/${WFO}_output
export COMINrtofs=${COMROOT}/${NET}/${envir}/ofs.${PDY}/rtofs/${WFO}_output
export COMINrtofsm1=${COMROOT}/${NET}/${envir}/ofs.${PDYm1}/rtofs/${WFO}_output
export COMINpsurge=${COMROOT}/${NET}/${envir}/ofs.${PDY}/psurge/${WFO}_output
export COMINpsurgem1=${COMROOT}/${NET}/${envir}/ofs.${PDYm1}/psurge/${WFO}_output
export dcom=${dcom:-/gpfs/${WCOSS_SYSTEM_COM}/dcomdev/us007003}
export FORECASTWINDdir="${dcom}/${PDY}/wgrbbul/${NET}"
export COM_nwps_R_ES_TOFS="/com"
export PCOM=${PCOMROOT}/${NET}/${envir}/${REGION}.${PDY}/${WFO}

if [ "${SENDCOM}" = YES ]; then
    mkdir -p $COMOUT
fi
mkdir -p $COMIN $LOGdir $RUNdir $TMPdir $OUTPUTdir $ARCHdir $DATAdir $INPUTdir $VARdir

startmsg

##############################################
# Execute the script
${HOMEnwps}/dev/scripts/exnwps_forecast.sh.ecf
##############################################

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg $jlogfile "$msg"

if [ -e $pgmout ]; then
    cat $pgmout
fi

cd $DATAROOT

if [ "$KEEPDATA" != YES ]; then
    rm -rf $DATA
fi

date
