#!/bin/bash
# ----------------------------------------------------------- 
# UNIX Shell Script File
# Tested Operating System(s): RHEL 5,6
# Tested Run Level(s): 3, 5
# Shell Used: BASH shell
# Original Author(s): Roberto Padilla-Hernandez
# File Creation Date: 05/09/2015
# Date Last Modified:
#
# Version control: 1.00
#
# Support Team:
#
# Contributors:
#
# ----------------------------------------------------------- 
# ------------- Program Description and Details ------------- 
# ----------------------------------------------------------- 
#
# Job Card to set the resources required for a NWPS run
#
# ----------------------------------------------------------- 

date
export PS4='$SECONDS ${0/\/nw.*\/nwps.*\/} + '
set -xa

# time step in Psurge data
#export TS_f=21600
export TS_f=3600

#AW curhour=$(date -u +%H)
#AW curhour=0
curhour=22
if [ $curhour -lt 12 ]; then CYCLE="00"; fi
if [ $curhour -ge 12 ] && [ $curhour -lt 18 ]; then CYCLE="06"; fi
if [ $curhour -ge 18 ] && [ $curhour -lt 22 ]; then CYCLE="12"; fi
if [ $curhour -ge 22 ]; then CYCLE="18"; fi
echo ""
echo "INFO - Current hour is ${curhour}, setting model cycle to ${CYCLE}"
export cyc=${CYCLE}
export cycle=t${cyc}z
export pgmout=OUTPUT.$$

export utilscript=${UTILROOT}/ush
export USHutil=${UTILROOT}/ush
#AW sh $utilscript/setpdy.sh

#AW . ./PDY
#export PDYm7=20170816
#export PDYm6=20170817
#export PDYm5=20170818
#export PDYm4=20170819
#export PDYm3=20170820
#export PDYm2=20170821
#export PDYm1=20170822
#export PDY=20170823
#export PDYp1=20170824
#export PDYp2=20170825
#export PDYp3=20170826
#export PDYp4=20170827
#export PDYp5=20170828
#export PDYp6=20170829
#export PDYp7=20170830

export PDYm7=20220118
export PDYm6=20220119
export PDYm5=20220120
export PDYm4=20220121
export PDYm3=20220122
export PDYm2=20220123
export PDYm1=20220124
export PDY=20220125
export PDYp1=20220126
export PDYp2=20220127
export PDYp3=20220128
export PDYp4=20220129
export PDYp5=20220130
export PDYp6=20220131
export PDYp7=20220201

sh $utilscript/setup.sh
export pgm="ofs.psurge"

####################################
# Specify NET and RUN Name and model
####################################
export NET=${model}
export OFS=ofs
export RUN=$(echo ${job}|awk -F"_" '{print $2}')

export DATA=/lfs/h2/emc/ptmp/${DEVWCOSS_USER}/$NET/$ver/ofs.${PDY}

mkdir -p $DATA
cd $DATA

####################################
# SENDECF  - Flag Events on ECFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEnwps=${HOMEnwps:-${NWROOT}/${model}.${nwps_ver}}
export FIXnwps=${FIXnwps:-${HOMEnwps}/fix}
export EXECnwps=${EXECnwps:-${HOMEnwps}/exec}
export SORCnwps=${SORCnwps:-${HOMEnwps}/sorc}
export PARMnwps=${PARMnwps:-${HOMEnwps}/parm}
export USHnwps=${USHnwps:-${HOMEnwps}/ush}

# Set processing DIRs here
export ARCHdir=${ARCHdir:-${DATA}/archive}
export INPUTdir=${INPUTdir:-${DATA}/input}
export VARdir=${VARdir:-${DATA}/var}
export OUTPUTdir=${OUTPUTdir:-${DATA}/output}
export RUNdir=${RUNdir:-${DATA}/run}
export TMPdir=${TMPdir:-${DATA}/tmp}
export LOGdir=${LOGdir:-${DATA}/logs}
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${HOMEnwps}/lib/szip:${HOMEnwps}/lib/proj

# Set NWPS run conditions
export DEBUGGING=${DEBUGGING:-TRUE}
export DEBUG_LEVEL=${DEBUG_LEVEL:-1}
export ISPRODUCTION=${ISPRODUCTION:-TRUE}
export SITETYPE=${SITETYPE:-EMC}

##############################################
# Define COM directory
##############################################
export COMIN=${COMROOT}/${NET}/${ver}/${OFS}.${PDY}
export COMOUT=${COMROOT}/${NET}/${ver}/${OFS}.${PDY}
export COMOUTm1=${COMROOT}/${NET}/${ver}/${OFS}.${PDYm1}
export GESOUT=${COMROOT}/${NET}/$ver/${NET}.${PDY}/nwges
#export COMINgfs=${COMROOT}/gfs/prod/gfs.${PDY}
#export COMINwave=${COMROOTp1}/wave/prod
#export COMINestofs=/gpfs/dell1/nco/ops/com/estofs/prod/estofs.${PDY}
#export COMINrtofs=${COMROOTp3}/rtofs/prod/rtofs.${PDY}
#export COMINsice=${COMROOTp3}/omb/prod/sice.${PDY}
#export COMINsicem1=${COMROOTp3}/omb/prod/sice.${PDYm1}
#export COMINpsurge=/gpfs/hps/nco/ops/com/psurge/prod/psurge.${PDY}
export COMINwave=/lfs/h2/emc/couple/noscrub/Andre.VanderWesthuysen/nwps/com/gfs/prod/
export COMINestofs=/lfs/h2/emc/couple/noscrub/Andre.VanderWesthuysen/nwps/com/estofs/prod/estofs.${PDY}
export COMINrtofs=/lfs/h2/emc/couple/noscrub/Andre.VanderWesthuysen/nwps/com/rtofs/prod/rtofs.${PDY}
export COMINsice=/lfs/h2/emc/couple/noscrub/Andre.VanderWesthuysen/nwps/com/omb/prod/sice.${PDY}
export COMINsicem1=/lfs/h2/emc/couple/noscrub/Andre.VanderWesthuysen/nwps/com/omb/prod/sice.${PDYm1}
export COMINpsurge=/gpfs/hps/nco/ops/com/psurge/prod/psurge.${PDY}

export COMROOTp2=/gpfs/hps/nco/ops/com

# TEST 1  (See ush/make_psurge_para.sh) 
#export COMINpsurge=${NWROOT}/com2/nhc/para
#----------------------------------------------------
# Test 2
#export COMINpsurge=$COMROOTp2/nhc/test/
#export DirIN=${COMINpsurge}/psurge.20150527/al082014
#----------------------------------------------------
#  TEST 3
#export COMINpsurge=$COMROOTp2/nhc/test/psurge.20150507/
#--------------------------------------------------
# TEST 4
#export COMINpsurge=${COMROOTp2}/nhc/para/psurge.20160406
#--------------------------------------------------
# PRODUCTION
# To work with the latest Psurge fields
#export COMINpsurge=$COMROOTp2/nhc/test/psurge.PDY
#export COMINpsurge=${COMROOTp2}/nhc/prod/psurge.${PDY}
#export COMINpsurge=/gpfs/hps/nco/ops/com/psurge/${envir}/psurge.${PDY}
#------------------------
# TEST 5
#export COMINpsurge=/gpfs/hps/nco/ops/com/psurge/para/psurge.20170403
#export COMINpsurge=/gpfs/hps/nco/ops/com/psurge/para/psurge.20170404
#export COMINpsurge=/gpfs/hps3/emc/marine/noscrub/Andre.VanderWesthuysen/nwps_para_20160501/psurge.20180501
#export COMINpsurge=/gpfs/hps/nco/ops/com/psurge/para/psurge.20200726
#export COMINpsurge=/gpfs/hps3/ptmp/Andre.VanderWesthuysen/data/psurge_tmp/
#------------------------
# TEST WCOSS2
#export COMINpsurge=/lfs/h1/mdl/marine/noscrub/Keep/psurge.v2.10/2018-Florence-Adv54-2.10.1/com/psurge/v2.10/psurge.20180912
#export COMINpsurge=/lfs/h1/mdl/marine/noscrub/Keep/psurge.v2.10/2017-Harvey-Adv12-2.10.1/com/psurge/v2.10/psurge.20170823/
export COMINpsurge=/lfs/h2/emc/couple/noscrub/Andre.VanderWesthuysen/nwps/com/psurge.v2.10/2017-Harvey-Adv12-2.10.1/com/psurge/v2.10/psurge.20170823/
#------------------------

export dcom=${dcom:-/dcom/us007003}
export COMOUTwmo=${COMROOT}/${NET}/${ver}/${REGION}.${PDY}/wmo

if [ "${SENDCOM}" = YES ]; then
    mkdir -p $COMOUT
fi

#mkdir -p  $LOGdir $RUNdir $TMPdir $OUTPUTdir $INPUTdir
mkdir -p $COMIN $LOGdir $RUNdir $TMPdir $OUTPUTdir $ARCHdir $DATAdir $INPUTdir $VARdir $GESOUT

##############################################
# Execute the script
${HOMEnwps}/dev/scripts/exnwps_ofs_prep.sh
##############################################

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg $jlogfile "$msg"

if [ -e $pgmout ]; then
    cat $pgmout
fi

cd $DATAROOT

if [ "$KEEPDATA" != YES ]; then
    rm -rf $DATA
fi

date
