#!/bin/bash
# ----------------------------------------------------------- 
# UNIX Shell Script File
# Tested Operating System(s): RHEL 5,6
# Tested Run Level(s): 3, 5
# Shell Used: BASH shell
# Original Author(s): Roberto Padilla-Hernandez
# File Creation Date: 05/09/2015
# Date Last Modified:
#
# Version control: 1.00
#
# Support Team:
#
# Contributors:
#
# ----------------------------------------------------------- 
# ------------- Program Description and Details ------------- 
# ----------------------------------------------------------- 
#
# Job Card to set the resources required for a NWPS run
#
# ----------------------------------------------------------- 

date
export PS4='$SECONDS ${0/\/nw.*\/nwps.*\/} + '
set -xa

# time step in Psurge data
#export TS_f=21600
export TS_f=3600

curhour=$(date -u +%H)
if [ $curhour -lt 12 ]; then CYCLE="00"; fi
if [ $curhour -ge 12 ] && [ $curhour -lt 18 ]; then CYCLE="06"; fi
if [ $curhour -ge 18 ] && [ $curhour -lt 22 ]; then CYCLE="12"; fi
if [ $curhour -ge 22 ]; then CYCLE="18"; fi
echo ""
echo "INFO - Current hour is ${curhour}, setting model cycle to ${CYCLE}"
export cyc=${CYCLE}
export cycle=t${cyc}z
export pgmout=OUTPUT.$$

export utilscript=/gpfs/hps/nco/ops/nwprod/prod_util.v1.0.3/ush
export USHutil=/gpfs/hps/nco/ops/nwprod/prod_util.v1.0.3/ush
sh $utilscript/setpdy.sh

. ./PDY

sh $utilscript/setup.sh
export pgm="ofs.psurge"

export DATA=/gpfs/hps/ptmp/${DEVWCOSS_USER}/data/ofs.${PDY}
#export COMROOT=${DATA}/com
export COMROOTp2=/gpfs/hps/nco/ops/com
export GESROOT=${DATA}/nwges

mkdir -p $DATA
cd $DATA

####################################
# Specify NET and RUN Name and model
####################################
export NET=${model}
export OFS=ofs
export RUN=$(echo ${job}|awk -F"_" '{print $2}')

####################################
# SENDECF  - Flag Events on ECFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
#export HOMEnwps=${NWROOT}/${model}.${nwps_ver}
export HOMEnwps=${NWROOT}
export NWPSdir=${NWROOT}
export FIXnwps=${FIXnwps:-${HOMEnwps}/fix}
export EXECnwps=${EXECnwps:-${HOMEnwps}/exec}
export SORCnwps=${SORCnwps:-${HOMEnwps}/sorc}
export PARMnwps=${PARMnwps:-${HOMEnwps}/parm}
export USHnwps=${USHnwps:-${HOMEnwps}/ush}

# Set processing DIRs here
export ARCHdir=${ARCHdir:-${DATA}/archive}
export INPUTdir=${INPUTdir:-${DATA}/input}
export VARdir=${VARdir:-${DATA}/var}
export OUTPUTdir=${OUTPUTdir:-${DATA}/output}
export RUNdir=${RUNdir:-${DATA}/run}
export TMPdir=${TMPdir:-${DATA}/tmp}
export LOGdir=${LOGdir:-${DATA}/logs}
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${HOMEnwps}/lib/szip:${HOMEnwps}/lib/proj

# Set NWPS run conditions
export DEBUGGING=${DEBUGGING:-TRUE}
export DEBUG_LEVEL=${DEBUG_LEVEL:-1}
export ISPRODUCTION=${ISPRODUCTION:-TRUE}
export SITETYPE=${SITETYPE:-EMC}

##############################################
# Define COM directory
##############################################
export COMIN=${COMROOT}/${NET}/${envir}/${OFS}.${PDY}
export COMOUT=${COMROOT}/${NET}/${envir}/${OFS}.${PDY}
export GESOUT=${GESROOT}/${envir}/${NET}.${PDY}
#export COMINgfs=${COMROOT}/gfs/prod/gfs.${PDY}
export COMINwave=${COMROOTp1}/wave/prod
export COMINestofs=${COMROOTp1}/estofs/prod/estofs.${PDY}
export COMINestofspac=${COMROOTp1}/estofs/prod/estofs_pac.${PDY}
export COMINrtofs=${COMROOTp1}/rtofs/prod/rtofs.${PDY}
export COMINsice=${COMROOTp1}/omb/prod/sice.${PDY}
export COMINsicem1=${COMROOTp1}/omb/prod/sice.${PDYm1}

# TEST 1  (See ush/make_psurge_para.sh) 
#export COMINpsurge=${NWROOT}/com2/nhc/para
#----------------------------------------------------
# Test 2
#export COMINpsurge=$COMROOTp2/nhc/test/
#export DirIN=${COMINpsurge}/psurge.20150527/al082014
#----------------------------------------------------
#  TEST 3
#export COMINpsurge=$COMROOTp2/nhc/test/psurge.20150507/
#--------------------------------------------------
# TEST 4
#export COMINpsurge=${COMROOTp2}/nhc/para/psurge.20160406
#--------------------------------------------------
# PRODUCTION
# To work with the latest Psurge fields
#export COMINpsurge=$COMROOTp2/nhc/test/psurge.PDY
export COMINpsurge=${COMROOTp2}/nhc/prod/psurge.${PDY}

export dcom=${dcom:-/dcom/us007003}
export PCOM=/pcom/${envir}/${NET}

if [ "${SENDCOM}" = YES ]; then
    mkdir -p $COMOUT
fi

#mkdir -p  $LOGdir $RUNdir $TMPdir $OUTPUTdir $INPUTdir
mkdir -p $COMIN $LOGdir $RUNdir $TMPdir $OUTPUTdir $ARCHdir $DATAdir $INPUTdir $VARdir $GESOUT

##############################################
# Execute the script
${HOMEnwps}/dev/scripts/exnwps_ofs_prep.sh.ecf
##############################################

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg $jlogfile "$msg"

if [ -e $pgmout ]; then
    cat $pgmout
fi

cd $DATAROOT

if [ "$KEEPDATA" != YES ]; then
    rm -rf $DATA
fi

date
