# NCEP Config file for global RTOFS and ESTOF init files

# RTOFS Domain for ocean currents
export RTOFSSECTOR="alaska"
# RTOFSDOMAIN="LON LAT 0. NX NY EW-RESOLUTION NS-RESOLUTION"
export RTOFSDOMAIN="215.50 53.90 0.0  495 235 0.029326 0.027027"
export RTOFSNX="496"
export RTOFSNY="236"

# ESTOFS Domain for water level
export ESTOFS_BASIN="estofs.pac"
export ESTOFS_REGION="alaska"
# ESFOTSDOMAIN="LON LAT 0. NX NY EW-RESOLUTION NS-RESOLUTION"
export ESTOFSDOMAIN="215.50 53.90 0.0  495 235 0.029326 0.027027"
export ESTOFSNX="496"
export ESTOFSNY="236"
export ESTOFSUSEICEMASK="TRUE"

# Sea ice domain
export SEAICEBLOCKDENS="0.5"
# SEAICEDOMAIN="LON LAT 0. NX NY EW-RESOLUTION NS-RESOLUTION"
export SEAICEDOMAIN="${ESTOFSDOMAIN}"
export SEAICENX="${ESTOFSNX}"
export SEAICENY="${ESTOFSNY}"
export SEAICEHOURS="${ESTOFSHOURS}"
export SEAICETIMESTEP="${ESTOFSTIMESTEP}"
