# NCEP Config file for global RTOFS and ESTOF init files

# RTOFS Domain for ocean currents
export RTOFSSECTOR="alaska"
# RTOFSDOMAIN="LON LAT 0. NX NY EW-RESOLUTION NS-RESOLUTION"
export RTOFSDOMAIN="182.50 52.65 0.0  873 365 0.029326 0.027027"
export RTOFSNX="874"
export RTOFSNY="366"

# ESTOFS Domain for water level
export ESTOFS_BASIN="estofs.pac"
export ESTOFS_REGION="alaska"
# ESFOTSDOMAIN="LON LAT 0. NX NY EW-RESOLUTION NS-RESOLUTION"
export ESTOFSDOMAIN="182.50 52.65 0.0  873 365 0.029326 0.027027"
export ESTOFSNX="874"
export ESTOFSNY="366"
export ESTOFSUSEICEMASK="TRUE"

# Sea ice domain
export SEAICEBLOCKDENS="0.5"
# SEAICEDOMAIN="LON LAT 0. NX NY EW-RESOLUTION NS-RESOLUTION"
export SEAICEDOMAIN="${ESTOFSDOMAIN}"
export SEAICENX="${ESTOFSNX}"
export SEAICENY="${ESTOFSNY}"
export SEAICEHOURS="${ESTOFSHOURS}"
export SEAICETIMESTEP="${ESTOFSTIMESTEP}"
