#%Module#######################################################################
# P-Surge v2.8.0                                        Last Change: 2020-04-22
#                                                        Arthur.Taylor@noaa.gov
#                                                              NWS/OSTI/MDL/DSB
###############################################################################
proc ModulesHelp { } {
   puts stderr "Set environment variables for P-Surge"
   puts stderr "This module initializes the user’s"
   puts stderr "environment to build the P-Surge model at NCEP"
}

module-whatis "P-Surge is a model to compute probabilistic storm surge and tide levels from tropical cyclones"

set ver v2.8.1
setenv B intel

# Need following for 'degrib'
setenv C_COMP icc

# Known conflicts
conflict PrgEnv-cray
conflict PrgEnv-gnu

#module unload PrgEnv-intel
module load PrgEnv-intel/5.2.82
#module load PrgEnv-intel/5.2.56

module unload intel
module load intel/18.1.163
#module load intel/14.0.3.174

module load iobuf/2.0.8

# Haswell should be faster than sandybridge, but not as easy to test.
module load zlib-intel-sandybridge/1.2.7
module load png-intel-sandybridge/1.2.49
module load jasper-gnu-sandybridge/1.900.1
module load g2c-intel/1.5.0

# module load zlib-intel-haswell/1.2.7
# module load png-intel-haswell/1.2.49
# module load jasper-gnu-haswell/1.900.1
# module load g2c-cray-haswell/1.5.0
