#!/bin/bash  
# --------------------------------------------------------------------------- #
#                                                                             #
# nwps_val.cron : Script manages the running of the NWPS validation script    #
#             ${workdir}/nwps_webgraph.sh                                     #
#                                                                             #
# Remarks   - Can be run interactively, or from LL.                           #
#                                                                             #
# Last Changed : 10-26-2015                                     October 2015  #
# --------------------------------------------------------------------------- #
#PBS -N nwps_hpss
#PBS -j oe
#PBS -S /bin/bash
#PBS -q dev_transfer
#PBS -A NWPS-DEV
#PBS -l walltime=06:00:00
#PBS -l select=1:ncpus=1
#PBS -l debug=true
#PBS -V
#PBS -o /u/andre.vanderwesthuysen/nwps_hpss.o
#PBS -e /u/andre.vanderwesthuysen/nwps_hpss.o

export HPSSDATE=$(date -d "-1 days" +%Y%m%d)
export DATADIR=/lfs/h2/emc/ptmp/$USER/com/nwps/v1.5.0
export HPSSOUT=/NCEPDEV/emc-marine
export TSM_FLAG="NO"
export CHECK_HPSS_IDX="YES"

${NWPSdir}/dev/scripts/rhist_savenwps.dev.sh ${DATADIR} ${HPSSDATE}
