#!/bin/bash --login
# --------------------------------------------------------------------------- #
#                                                                             #
# nwps_val.cron : Script manages the running of the NWPS validation script    #
#             ${workdir}/nwps_webgraph.sh                                     #
#                                                                             #
# Remarks   - Can be run interactively, or from LL.                           #
#                                                                             #
# Last Changed : 10-26-2015                                     October 2015  #
# --------------------------------------------------------------------------- #
#PBS -N nwps_ftp
#PBS -j oe
#PBS -S /bin/bash
#PBS -q dev_transfer
#PBS -A NWPS-DEV
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=1
#PBS -l debug=true
#PBS -V
#PBS -o /u/andre.vanderwesthuysen/nwps_ftp_all.o
#PBS -e /u/andre.vanderwesthuysen/nwps_ftp_all.o

/u/$USER/nwps_ftp_all_prod.sh > ${HOME}/nwps_ftp_all_prod.log 2>&1
