#!/bin/sh
prefix=/gpfs/hps/emc/marine/noscrub/Andre.VanderWesthuysen/NWPS/WCOSS_incl_WR_PR_AR/lib/basemap
exec_prefix=${prefix}
libdir=/gpfs/hps/emc/marine/noscrub/Andre.VanderWesthuysen/NWPS/WCOSS_incl_WR_PR_AR/lib/basemap

usage()
{
    cat <<EOF
Usage: geos-config [OPTIONS]
Options:
     [--prefix]
     [--version]
     [--libs]
     [--clibs]
     [--cflags]
     [--ldflags]
     [--includes]
     [--jtsport]
EOF
    exit $1
}
if test $# -eq 0; then
  usage 1 1>&2
fi
while test $# -gt 0; do
case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
esac
case $1 in
    --prefix)
    echo ${prefix}
     ;;
    --version)
    echo 3.3.3
     ;;
    --cflags)
    echo -I${prefix}/include 
      ;;
    --libs)
      echo -L${libdir} -lgeos
      ;;
    --clibs)
      echo -L${libdir} -lgeos_c
      ;;
    --ldflags)
      echo -L${libdir}
      ;;
    --includes)
      echo ${prefix}/include
      ;;
    --jtsport)
    echo 1.12.0 
      ;;
    *)
      usage 1 1>&2
      ;;
  esac
  shift
done

